config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :ratings
  resources :tabs
  resources :chords
  delete '/logout', to: 'sessions#destroy'
  get 'sessions/new'

  root to: "users#index"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  
  post '/favorites', to: 'tabs#favorites'

  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chord.rb
class Chord < ApplicationRecord
	serialize :positions, Array
	serialize :fingering, Array

	has_many :chord_tabs
	has_many :tabs, through: :chord_tabs
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  before_action :set_chord, only: [:show, :edit, :update, :destroy]

  # GET /chords
  # GET /chords.json
  def index
    @chords = Chord.all
  end

  # GET /chords/1
  # GET /chords/1.json
  def show
    @chord = Chord.find params[:id]
  end

  # GET /chords/new
  def new
    @chord = Chord.new
  end

  # GET /chords/1/edit
  def edit
  end

  # POST /chords
  # POST /chords.json
  def create
    @chord = Chord.new(chord_params)

    respond_to do |format|
      if @chord.save
        format.html { redirect_to @chord, notice: 'Chord was successfully created.' }
        format.json { render :show, status: :created, location: @chord }
      else
        format.html { render :new }
        format.json { render json: @chord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chords/1
  # PATCH/PUT /chords/1.json
  def update
    respond_to do |format|
      if @chord.update(chord_params)
        format.html { redirect_to @chord, notice: 'Chord was successfully updated.' }
        format.json { render :show, status: :ok, location: @chord }
      else
        format.html { render :edit }
        format.json { render json: @chord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chords/1
  # DELETE /chords/1.json
  def destroy
    @chord.destroy
    respond_to do |format|
      format.html { redirect_to chords_url, notice: 'Chord was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chord
      @chord = Chord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chord_params
      params.require(:chord).permit(:root, :chord_type, :barre, :barre_position, :positions, :fingering)
    end
end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/views/chords/_form.html.erb
<%= form_with(model: chord, local: true) do |form| %>
  <% if chord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chord.errors.count, "error") %> prohibited this chord from being saved:</h2>

      <ul>
      <% chord.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% @chord.attributes.except('id', 'created_at', 'updated_at').keys.each do |attr| %>
    <%= form.label attr %>
    <%= form.text_field attr %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chords/edit.html.erb
<h1>Editing Chord</h1>

<%= render 'form', chord: @chord %>

<%= link_to 'Show', @chord %> |
<%= link_to 'Back', chords_path %>

app/views/chords/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chords</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chords.each do |chord| %>
      <tr>
        <td><%= link_to 'Show', chord %></td>
        <td><%= link_to 'Edit', edit_chord_path(chord) %></td>
        <td><%= link_to 'Destroy', chord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chord', new_chord_path %>

app/views/chords/new.html.erb
<h1>New Chord</h1>

<%= render 'form', chord: @chord %>

<%= link_to 'Back', chords_path %>

app/views/chords/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chord_path(@chord) %> |
<%= link_to 'Back', chords_path %>
<p class='chord' data-positions='<%=@chord.positions%>' data-fingering='<%=@chord.fingering%>' > <%="#{@chord.root}#{@chord.chord_type}"%></p>